# Generated by Django 4.2.4 on 2023-10-26 13:10

import brokers.models
from django.db import migrations, models
import django.db.models.deletion
import ectype_bend_beta.model_utils


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EctypeBroker",
            fields=[
                (
                    "uid",
                    models.CharField(
                        default=ectype_bend_beta.model_utils.generate_id,
                        editable=False,
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="active"
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        default=brokers.models.generate_id,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tradesync_broker_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("mt_version", models.CharField(max_length=10)),
            ],
            options={
                "ordering": ["-created_at", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EctypeBrokerServer",
            fields=[
                (
                    "uid",
                    models.CharField(
                        default=ectype_bend_beta.model_utils.generate_id,
                        editable=False,
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="active"
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        default=brokers.models.generate_id,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tradesync_brokerserver_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("mt_version", models.CharField(max_length=10)),
                (
                    "broker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="ectypebroker",
                        to="brokers.ectypebroker",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
                "abstract": False,
            },
        ),
    ]
