# Generated by Django 4.2.4 on 2023-10-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brokers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ectypebrokerserver",
            name="broker",
        ),
        migrations.AddField(
            model_name="ectypebrokerserver",
            name="broker_id",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
