# Generated by Django 4.2.4 on 2023-11-04 05:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("brokers", "0002_remove_ectypebrokerserver_broker_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ectypebroker",
            options={},
        ),
        migrations.AlterModelOptions(
            name="ectypebrokerserver",
            options={},
        ),
        migrations.RemoveField(
            model_name="ectypebroker",
            name="active",
        ),
        migrations.RemoveField(
            model_name="ectypebroker",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="ectypebroker",
            name="uid",
        ),
        migrations.RemoveField(
            model_name="ectypebroker",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="ectypebrokerserver",
            name="active",
        ),
        migrations.RemoveField(
            model_name="ectypebrokerserver",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="ectypebrokerserver",
            name="uid",
        ),
        migrations.RemoveField(
            model_name="ectypebrokerserver",
            name="updated_at",
        ),
    ]
