# Generated by Django 4.2.4 on 2023-12-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referred_by",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Referrer Email"
            ),
        ),
    ]
