# Generated by Django 4.2.4 on 2023-12-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_referred_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
