# Generated by Django 4.2.4 on 2023-11-30 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ectype_bend_beta.model_utils


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("referral", "0002_alter_referraltoken_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralPayment",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=ectype_bend_beta.model_utils.generate_id,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        default=ectype_bend_beta.model_utils.generate_id,
                        editable=False,
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="active"
                    ),
                ),
                (
                    "cash_out",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("paid_referrals", models.IntegerField(default=0)),
                ("unpaid_referrals", models.IntegerField(default=0)),
                (
                    "owner",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referralpaymant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
                "abstract": False,
            },
        ),
    ]
