# Generated by Django 4.2.4 on 2023-10-26 13:11

import accounts.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EctypeTradeAccountCopier",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=accounts.models.generate_id,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lead_id", models.CharField(max_length=150)),
                ("follower_id", models.CharField(max_length=150)),
                ("risk_multiplier", models.CharField(max_length=150)),
                (
                    "risk_type",
                    models.CharField(
                        choices=[
                            (
                                "risk_multiplier_by_balance",
                                "Risk Multiplier By Balance",
                            ),
                            ("risk_multiplier_by_equity", "Risk Multiplier By Equity"),
                            ("risk_multiplier_by_trade", "Risk Multiplier By Trade"),
                            ("lot_multiplier", "Lot Multiplier"),
                            ("fixed_lot", "Fixed Lot"),
                            (
                                "percentage_risk_per_trade_by_balance",
                                "Percentage Risk Per Trade By Balance",
                            ),
                            (
                                "percentage_risk_per_trade_by_equity",
                                "Percentage Risk Per Trade By Equity",
                            ),
                        ],
                        default="risk_multiplier_by_balance",
                        max_length=150,
                    ),
                ),
                ("tradesync_copier_id", models.CharField(max_length=150)),
                (
                    "mode",
                    models.CharField(
                        choices=[("off", "Off"), ("on", "On"), ("monitor", "Monitor")],
                        default="off",
                        max_length=50,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 10, 26, 14, 11, 46, 927679)
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trading_account_copier",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EctypeTradeAccount",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=accounts.models.generate_id,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tradesync_account_id", models.CharField(max_length=150)),
                ("account_name", models.CharField(max_length=250)),
                (
                    "account_type",
                    models.CharField(
                        choices=[("UNKNOWN", "UNKNOWN"), ("4", "MT4"), ("5", "MT5")],
                        default="UNKNOWN",
                        max_length=150,
                    ),
                ),
                ("account_number", models.CharField(max_length=250)),
                ("account_password", models.CharField(max_length=250)),
                ("broker_name", models.CharField(max_length=150)),
                ("broker_server", models.CharField(max_length=250)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=accounts.models.get_default_metadata,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 10, 26, 14, 11, 46, 927034)
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trading_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
