# Generated by Django 4.2.4 on 2023-11-04 05:38

import accounts.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0002_alter_ectypetradeaccount_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeSyncCopier",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=accounts.models.generate_id,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tradesync_copier_id", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="ectypetradeaccount",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 4, 6, 38, 18, 237596)
            ),
        ),
        migrations.AlterField(
            model_name="ectypetradeaccountcopier",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 4, 6, 38, 18, 240193)
            ),
        ),
        migrations.AlterField(
            model_name="ectypetradeaccountcopier",
            name="risk_type",
            field=models.CharField(
                choices=[
                    ("risk_multiplier_by_balance", "Risk Multiplier By Balance"),
                    ("risk_multiplier_by_equity", "Risk Multiplier By Equity"),
                    ("risk_amount_per_trade", "Risk Multiplier By Trade"),
                    ("lot_multiplier", "Lot Multiplier"),
                    ("fixed_lot", "Fixed Lot"),
                    (
                        "percentage_risk_per_trade_by_balance",
                        "Percentage Risk Per Trade By Balance",
                    ),
                    (
                        "percentage_risk_per_trade_by_equity",
                        "Percentage Risk Per Trade By Equity",
                    ),
                ],
                default="risk_multiplier_by_balance",
                max_length=150,
            ),
        ),
        migrations.CreateModel(
            name="EctypeCopierTrade",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=accounts.models.generate_id,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lead_id", models.CharField(max_length=150)),
                ("risk_multiplier", models.CharField(max_length=150)),
                (
                    "risk_type",
                    models.CharField(
                        choices=[
                            (
                                "risk_multiplier_by_balance",
                                "Risk Multiplier By Balance",
                            ),
                            ("risk_multiplier_by_equity", "Risk Multiplier By Equity"),
                            ("risk_amount_per_trade", "Risk Multiplier By Trade"),
                            ("lot_multiplier", "Lot Multiplier"),
                            ("fixed_lot", "Fixed Lot"),
                            (
                                "percentage_risk_per_trade_by_balance",
                                "Percentage Risk Per Trade By Balance",
                            ),
                            (
                                "percentage_risk_per_trade_by_equity",
                                "Percentage Risk Per Trade By Equity",
                            ),
                        ],
                        default="risk_multiplier_by_balance",
                        max_length=150,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("off", "Off"), ("on", "On"), ("monitor", "Monitor")],
                        default="off",
                        max_length=50,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "follower_ids",
                    models.ManyToManyField(
                        blank=True,
                        related_name="copier_followers",
                        to="accounts.ectypetradeaccount",
                    ),
                ),
                (
                    "trade_sync_copier_ids",
                    models.ManyToManyField(
                        blank=True,
                        related_name="associated_copiers",
                        to="accounts.tradesynccopier",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copier_trades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
