# Generated by Django 4.2.4 on 2023-11-04 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0003_tradesynccopier_alter_ectypetradeaccount_created_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ectypecopiertrade",
            name="follower_ids",
        ),
        migrations.RemoveField(
            model_name="ectypecopiertrade",
            name="trade_sync_copier_ids",
        ),
        migrations.AlterField(
            model_name="ectypetradeaccount",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 4, 8, 35, 24, 666133)
            ),
        ),
        migrations.AlterField(
            model_name="ectypetradeaccountcopier",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 4, 8, 35, 24, 667454)
            ),
        ),
        migrations.DeleteModel(
            name="TradeSyncCopier",
        ),
        migrations.AddField(
            model_name="ectypecopiertrade",
            name="follower_ids",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="ectypecopiertrade",
            name="trade_sync_copier_ids",
            field=models.JSONField(default=dict),
        ),
    ]
