# Generated by Django 4.2.4 on 2023-11-04 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_ectypecopiertrade_follower_ids_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ectypecopiertrade",
            name="trade_sync_copier_ids",
        ),
        migrations.AlterField(
            model_name="ectypetradeaccount",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 4, 10, 26, 46, 462122)
            ),
        ),
        migrations.AlterField(
            model_name="ectypetradeaccountcopier",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 4, 10, 26, 46, 463121)
            ),
        ),
    ]
