# Generated by Django 4.2.4 on 2023-11-07 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_ectypecopiertrade_metadata_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ectypetradeaccount",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 7, 10, 17, 32, 416368)
            ),
        ),
        migrations.DeleteModel(
            name="EctypeTradeAccountCopier",
        ),
    ]
