# Generated by Django 4.2.4 on 2023-11-20 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_ectypetradeaccount_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ectypetradeaccount",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 20, 15, 48, 35, 196770)
            ),
        ),
    ]
